# Generated by Django 4.1.2 on 2022-10-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ürün',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('index', models.IntegerField()),
                ('Img', models.CharField(max_length=300)),
                ('Marka', models.CharField(blank=True, max_length=100)),
                ('BellekHızı', models.CharField(blank=True, max_length=20)),
                ('HDMI', models.CharField(blank=True, max_length=20)),
                ('EkranKartıBellekTipi', models.CharField(blank=True, max_length=20)),
                ('Renk', models.CharField(blank=True, max_length=20)),
                ('RamTipi', models.CharField(blank=True, max_length=50)),
                ('HepsiBuradaPrice', models.FloatField()),
                ('HepsiBuradaURL', models.CharField(max_length=300)),
                ('HepsiBuradaRating', models.FloatField(blank=True)),
                ('teknosaPrice', models.FloatField()),
                ('teknosaURL', models.CharField(max_length=300)),
                ('teknosaRating', models.FloatField(blank=True)),
                ('AmazonPrice', models.FloatField()),
                ('AmazonURL', models.CharField(max_length=300)),
                ('AmazonRating', models.FloatField(blank=True)),
                ('vatanBilgisayarPrice', models.FloatField()),
                ('vatanBilgisayarURL', models.CharField(max_length=300)),
                ('vatanBilgisayarRating', models.FloatField(blank=True)),
                ('cicekSepetiExtraPrice', models.FloatField()),
                ('cicekSepetiExtraURL', models.CharField(max_length=300)),
                ('cicekSepetiExtraRating', models.FloatField(blank=True)),
                ('TrendyolPrice', models.FloatField()),
                ('TrendyolURL', models.CharField(max_length=300)),
                ('TrendyolRating', models.FloatField(blank=True)),
                ('n11Price', models.FloatField()),
                ('n11URL', models.CharField(max_length=300)),
                ('n11Rating', models.FloatField(blank=True)),
            ],
        ),
    ]
