# Generated by Django 4.1.2 on 2022-10-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bilgisayar',
            fields=[
                ('bilgisayarId', models.AutoField(primary_key=True, serialize=False)),
                ('marka', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('ram', models.IntegerField()),
                ('ssd', models.IntegerField()),
            ],
        ),
    ]
