# Generated by Django 3.1.12 on 2022-10-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ürünler',
            name='ağırlık',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ürünler',
            name='bellek_hızı',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ürünler',
            name='dos',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ürünler',
            name='ekran_kartı',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ürünler',
            name='işlemci',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ürünler',
            name='marka',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ürünler',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ürünler',
            name='ram',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ürünler',
            name='renk',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
