# Generated by Django 4.1.2 on 2022-10-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PC',
            fields=[
                ('pcId', models.AutoField(primary_key=True, serialize=False)),
                ('isim', models.CharField(max_length=200)),
                ('fiyat1', models.FloatField()),
                ('fiyat2', models.FloatField()),
                ('fiyat3', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Bilgisayar',
        ),
    ]
