# Generated by Django 4.1.2 on 2022-10-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0002_pc_delete_bilgisayar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bilg',
            fields=[
                ('pcId', models.AutoField(primary_key=True, serialize=False)),
                ('isim', models.CharField(max_length=200)),
                ('fiyat1', models.FloatField()),
                ('fiyat2', models.FloatField()),
                ('fiyat3', models.FloatField()),
                ('image', models.ImageField(upload_to='static/pc_img')),
            ],
        ),
        migrations.DeleteModel(
            name='PC',
        ),
    ]
