# Generated by Django 4.1.2 on 2022-10-24 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0003_bilg_delete_pc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bilg',
        ),
    ]
